sonar.projectKey=GAUNET-Aline
sonar.projectName=GAUNET Aline - breakableflask
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.exclusions=**/.git/**,**/.github/**,**/__pycache__/**,**/*.md,**/.venv/**,**/venv/**